version: "3"

volumes:
  db-data:

services:
  db:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    ports:
      - 1090:80
    volumes:
      - ./phpmyadmin/sessions:/sessions

  php:
    build: ./php
    volumes:
      - ./nginx/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - db

  nginx:
    image: nginx
    volumes:
      - ./nginx/passswd:/etc/nginx/passswd
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/var/www/html
    restart: always
    ports:
      - 1000:80
    depends_on:
      - php
